#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DataLayer;
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace WcfService.Dto
{
	public interface IDtoWithKey
	{
		string DtoKey { get; set; }
	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ClienteDto))]
	[KnownType(typeof(AnagraficaClienteDto))]
	[KnownType(typeof(SocioDto))]
	[KnownType(typeof(AccountDto))]
	public partial class AziendaDto : IDtoWithKey
	{
		public AziendaDto()
		{
		}
		
		public AziendaDto(int _id, string _ragioneSociale, string _indirizzo, string _cAP, string _comune, string _provincia, string _partitaIva, string _telefono, string _fax, string _email, string _codiceCatastale, string _pEC, string _codice, IList<ClienteDto> _clientes, IList<AnagraficaClienteDto> _anagraficaClientes, IList<SocioDto> _socios, IList<AccountDto> _accounts)
		{
			this.Id = _id;
			this.RagioneSociale = _ragioneSociale;
			this.Indirizzo = _indirizzo;
			this.CAP = _cAP;
			this.Comune = _comune;
			this.Provincia = _provincia;
			this.PartitaIva = _partitaIva;
			this.Telefono = _telefono;
			this.Fax = _fax;
			this.Email = _email;
			this.CodiceCatastale = _codiceCatastale;
			this.PEC = _pEC;
			this.Codice = _codice;
			this.Clientes = _clientes;
			this.AnagraficaClientes = _anagraficaClientes;
			this.Socios = _socios;
			this.Accounts = _accounts;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string RagioneSociale { get;set; }

		[DataMember]
		public virtual string Indirizzo { get;set; }

		[DataMember]
		public virtual string CAP { get;set; }

		[DataMember]
		public virtual string Comune { get;set; }

		[DataMember]
		public virtual string Provincia { get;set; }

		[DataMember]
		public virtual string PartitaIva { get;set; }

		[DataMember]
		public virtual string Telefono { get;set; }

		[DataMember]
		public virtual string Fax { get;set; }

		[DataMember]
		public virtual string Email { get;set; }

		[DataMember]
		public virtual string CodiceCatastale { get;set; }

		[DataMember]
		public virtual string PEC { get;set; }

		[DataMember]
		public virtual string Codice { get;set; }

		[DataMember]
		public virtual IList<ClienteDto> Clientes { get;set; }

		[DataMember]
		public virtual IList<AnagraficaClienteDto> AnagraficaClientes { get;set; }

		[DataMember]
		public virtual IList<SocioDto> Socios { get;set; }

		[DataMember]
		public virtual IList<AccountDto> Accounts { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(AziendaDto))]
	[KnownType(typeof(AnagraficaClienteDto))]
	[KnownType(typeof(AnagraficaPADto))]
	[KnownType(typeof(FatturaDto))]
	public partial class ClienteDto : IDtoWithKey
	{
		public ClienteDto()
		{
		}
		
		public ClienteDto(int _id, int _aziendaId, int _anagraficaClienteId, int _anagraficaPAId, string _tipo, AziendaDto _azienda, AnagraficaClienteDto _anagraficaCliente, AnagraficaPADto _anagraficaPA, IList<FatturaDto> _fatturas)
		{
			this.Id = _id;
			this.AziendaId = _aziendaId;
			this.AnagraficaClienteId = _anagraficaClienteId;
			this.AnagraficaPAId = _anagraficaPAId;
			this.Tipo = _tipo;
			this.Azienda = _azienda;
			this.AnagraficaCliente = _anagraficaCliente;
			this.AnagraficaPA = _anagraficaPA;
			this.Fatturas = _fatturas;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int AziendaId { get;set; }

		[DataMember]
		public virtual int AnagraficaClienteId { get;set; }

		[DataMember]
		public virtual int AnagraficaPAId { get;set; }

		[DataMember]
		public virtual string Tipo { get;set; }

		[DataMember]
		public virtual AziendaDto Azienda { get;set; }

		[DataMember]
		public virtual AnagraficaClienteDto AnagraficaCliente { get;set; }

		[DataMember]
		public virtual AnagraficaPADto AnagraficaPA { get;set; }

		[DataMember]
		public virtual IList<FatturaDto> Fatturas { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ClienteDto))]
	[KnownType(typeof(TrasmissioneDto))]
	[KnownType(typeof(IncassoDto))]
	[KnownType(typeof(FatturaElettronicaHeaderDto))]
	[KnownType(typeof(FatturaElettronicaBodyDto))]
	public partial class FatturaDto : IDtoWithKey
	{
		public FatturaDto()
		{
		}
		
		public FatturaDto(int _id, int _clienteId, ClienteDto _cliente, IList<TrasmissioneDto> _trasmissiones, IList<IncassoDto> _incassos, FatturaElettronicaHeaderDto _fatturaElettronicaHeader, FatturaElettronicaBodyDto _fatturaElettronicaBody)
		{
			this.Id = _id;
			this.ClienteId = _clienteId;
			this.Cliente = _cliente;
			this.Trasmissiones = _trasmissiones;
			this.Incassos = _incassos;
			this.FatturaElettronicaHeader = _fatturaElettronicaHeader;
			this.FatturaElettronicaBody = _fatturaElettronicaBody;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int ClienteId { get;set; }

		[DataMember]
		public virtual ClienteDto Cliente { get;set; }

		[DataMember]
		public virtual IList<TrasmissioneDto> Trasmissiones { get;set; }

		[DataMember]
		public virtual IList<IncassoDto> Incassos { get;set; }

		[DataMember]
		public virtual FatturaElettronicaHeaderDto FatturaElettronicaHeader { get;set; }

		[DataMember]
		public virtual FatturaElettronicaBodyDto FatturaElettronicaBody { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(FatturaDto))]
	public partial class TrasmissioneDto : IDtoWithKey
	{
		public TrasmissioneDto()
		{
		}
		
		public TrasmissioneDto(int _id, int _fatturaId, FatturaDto _fattura)
		{
			this.Id = _id;
			this.FatturaId = _fatturaId;
			this.Fattura = _fattura;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int FatturaId { get;set; }

		[DataMember]
		public virtual FatturaDto Fattura { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(AziendaDto))]
	[KnownType(typeof(ClienteDto))]
	public partial class AnagraficaClienteDto : IDtoWithKey
	{
		public AnagraficaClienteDto()
		{
		}
		
		public AnagraficaClienteDto(int _id, int _aziendaId, string _ragioneSociale, string _cognome, AziendaDto _azienda, IList<ClienteDto> _clientes)
		{
			this.Id = _id;
			this.AziendaId = _aziendaId;
			this.RagioneSociale = _ragioneSociale;
			this.Cognome = _cognome;
			this.Azienda = _azienda;
			this.Clientes = _clientes;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int AziendaId { get;set; }

		[DataMember]
		public virtual string RagioneSociale { get;set; }

		[DataMember]
		public virtual string Cognome { get;set; }

		[DataMember]
		public virtual AziendaDto Azienda { get;set; }

		[DataMember]
		public virtual IList<ClienteDto> Clientes { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(FatturaDto))]
	public partial class IncassoDto : IDtoWithKey
	{
		public IncassoDto()
		{
		}
		
		public IncassoDto(int _id, int _fatturaId, FatturaDto _fattura)
		{
			this.Id = _id;
			this.FatturaId = _fatturaId;
			this.Fattura = _fattura;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int FatturaId { get;set; }

		[DataMember]
		public virtual FatturaDto Fattura { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(AziendaDto))]
	public partial class SocioDto : IDtoWithKey
	{
		public SocioDto()
		{
		}
		
		public SocioDto(int _id, int _aziendaId, string _cognome, string _nome, string _tipoCarica, AziendaDto _azienda)
		{
			this.Id = _id;
			this.AziendaId = _aziendaId;
			this.Cognome = _cognome;
			this.Nome = _nome;
			this.TipoCarica = _tipoCarica;
			this.Azienda = _azienda;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int AziendaId { get;set; }

		[DataMember]
		public virtual string Cognome { get;set; }

		[DataMember]
		public virtual string Nome { get;set; }

		[DataMember]
		public virtual string TipoCarica { get;set; }

		[DataMember]
		public virtual AziendaDto Azienda { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ClienteDto))]
	public partial class AnagraficaPADto : IDtoWithKey
	{
		public AnagraficaPADto()
		{
		}
		
		public AnagraficaPADto(int _id, string _codice, string _denominazione, string _comune, string _nomeResponsabile, string _cognomeResponsabile, int _cAP, string _provincia, string _regione, string _sitoIstituzionale, string _indirizzo, string _titoloResponsabile, string _tipologiaIstat, string _tipologiaAmministrazione, string _acronimo, bool _cfValidato, string _codiceFiscale, string _email1, IList<ClienteDto> _clientes)
		{
			this.Id = _id;
			this.Codice = _codice;
			this.Denominazione = _denominazione;
			this.Comune = _comune;
			this.NomeResponsabile = _nomeResponsabile;
			this.CognomeResponsabile = _cognomeResponsabile;
			this.CAP = _cAP;
			this.Provincia = _provincia;
			this.Regione = _regione;
			this.SitoIstituzionale = _sitoIstituzionale;
			this.Indirizzo = _indirizzo;
			this.TitoloResponsabile = _titoloResponsabile;
			this.TipologiaIstat = _tipologiaIstat;
			this.TipologiaAmministrazione = _tipologiaAmministrazione;
			this.Acronimo = _acronimo;
			this.CfValidato = _cfValidato;
			this.CodiceFiscale = _codiceFiscale;
			this.email1 = _email1;
			this.Clientes = _clientes;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string Codice { get;set; }

		[DataMember]
		public virtual string Denominazione { get;set; }

		[DataMember]
		public virtual string Comune { get;set; }

		[DataMember]
		public virtual string NomeResponsabile { get;set; }

		[DataMember]
		public virtual string CognomeResponsabile { get;set; }

		[DataMember]
		public virtual int CAP { get;set; }

		[DataMember]
		public virtual string Provincia { get;set; }

		[DataMember]
		public virtual string Regione { get;set; }

		[DataMember]
		public virtual string SitoIstituzionale { get;set; }

		[DataMember]
		public virtual string Indirizzo { get;set; }

		[DataMember]
		public virtual string TitoloResponsabile { get;set; }

		[DataMember]
		public virtual string TipologiaIstat { get;set; }

		[DataMember]
		public virtual string TipologiaAmministrazione { get;set; }

		[DataMember]
		public virtual string Acronimo { get;set; }

		[DataMember]
		public virtual bool CfValidato { get;set; }

		[DataMember]
		public virtual string CodiceFiscale { get;set; }

		[DataMember]
		public virtual string email1 { get;set; }

		[DataMember]
		public virtual IList<ClienteDto> Clientes { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(FatturaDto))]
	[KnownType(typeof(DatiTrasmissioneDto))]
	public partial class FatturaElettronicaHeaderDto : IDtoWithKey
	{
		public FatturaElettronicaHeaderDto()
		{
		}
		
		public FatturaElettronicaHeaderDto(int _id, FatturaDto _fattura, DatiTrasmissioneDto _datiTrasmissione)
		{
			this.Id = _id;
			this.Fattura = _fattura;
			this.DatiTrasmissione = _datiTrasmissione;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual FatturaDto Fattura { get;set; }

		[DataMember]
		public virtual DatiTrasmissioneDto DatiTrasmissione { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(FatturaDto))]
	public partial class FatturaElettronicaBodyDto : IDtoWithKey
	{
		public FatturaElettronicaBodyDto()
		{
		}
		
		public FatturaElettronicaBodyDto(int _id, FatturaDto _fattura)
		{
			this.Id = _id;
			this.Fattura = _fattura;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual FatturaDto Fattura { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(FatturaElettronicaHeaderDto))]
	[KnownType(typeof(IdTrasmissioneDto))]
	public partial class DatiTrasmissioneDto : IDtoWithKey
	{
		public DatiTrasmissioneDto()
		{
		}
		
		public DatiTrasmissioneDto(int _id, string _progressivoInvio, string _formatoTrasmissione, string _codiceDestinatario, FatturaElettronicaHeaderDto _fatturaElettronicaHeader, IdTrasmissioneDto _idTrasmissione)
		{
			this.Id = _id;
			this.ProgressivoInvio = _progressivoInvio;
			this.FormatoTrasmissione = _formatoTrasmissione;
			this.CodiceDestinatario = _codiceDestinatario;
			this.FatturaElettronicaHeader = _fatturaElettronicaHeader;
			this.IdTrasmissione = _idTrasmissione;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string ProgressivoInvio { get;set; }

		[DataMember]
		public virtual string FormatoTrasmissione { get;set; }

		[DataMember]
		public virtual string CodiceDestinatario { get;set; }

		[DataMember]
		public virtual FatturaElettronicaHeaderDto FatturaElettronicaHeader { get;set; }

		[DataMember]
		public virtual IdTrasmissioneDto IdTrasmissione { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(DatiTrasmissioneDto))]
	public partial class IdTrasmissioneDto : IDtoWithKey
	{
		public IdTrasmissioneDto()
		{
		}
		
		public IdTrasmissioneDto(int _id, string _idPaese, string _idCodice, DatiTrasmissioneDto _datiTrasmissione)
		{
			this.Id = _id;
			this.IdPaese = _idPaese;
			this.IdCodice = _idCodice;
			this.DatiTrasmissione = _datiTrasmissione;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string IdPaese { get;set; }

		[DataMember]
		public virtual string IdCodice { get;set; }

		[DataMember]
		public virtual DatiTrasmissioneDto DatiTrasmissione { get;set; }

	}
	
	[DataContract(IsReference = true)]
	public partial class ContattiTrasmittenteDto : IDtoWithKey
	{
		public ContattiTrasmittenteDto()
		{
		}
		
		public ContattiTrasmittenteDto(int _id, string _telefono, string _email)
		{
			this.Id = _id;
			this.Telefono = _telefono;
			this.Email = _email;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string Telefono { get;set; }

		[DataMember]
		public virtual string Email { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(AziendaDto))]
	public partial class AccountDto : IDtoWithKey
	{
		public AccountDto()
		{
		}
		
		public AccountDto(int _id, int _studioAziendaId, string _username, string _password, string _nickname, string _ruolo, string _note, DateTime _creazione, bool _abilitato, AziendaDto _azienda)
		{
			this.Id = _id;
			this.StudioAziendaId = _studioAziendaId;
			this.Username = _username;
			this.Password = _password;
			this.Nickname = _nickname;
			this.Ruolo = _ruolo;
			this.Note = _note;
			this.Creazione = _creazione;
			this.Abilitato = _abilitato;
			this.Azienda = _azienda;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int StudioAziendaId { get;set; }

		[DataMember]
		public virtual string Username { get;set; }

		[DataMember]
		public virtual string Password { get;set; }

		[DataMember]
		public virtual string Nickname { get;set; }

		[DataMember]
		public virtual string Ruolo { get;set; }

		[DataMember]
		public virtual string Note { get;set; }

		[DataMember]
		public virtual DateTime Creazione { get;set; }

		[DataMember]
		public virtual bool Abilitato { get;set; }

		[DataMember]
		public virtual AziendaDto Azienda { get;set; }

	}
	
}
#pragma warning restore 1591
