#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DataLayer;
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace WcfService.Dto
{
	public interface IDtoWithKey
	{
		string DtoKey { get; set; }
	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ClienteDto))]
	[KnownType(typeof(SocioDto))]
	[KnownType(typeof(AnagraficaClienteDto))]
	[KnownType(typeof(AccountDto))]
	public partial class AziendaDto : IDtoWithKey
	{
		public AziendaDto()
		{
		}
		
		public AziendaDto(int _id, string _ragioneSociale, string _indirizzo, string _cAP, string _comune, string _provincia, string _partitaIva, string _telefono, string _fax, string _email, string _codiceCatastale, string _pEC, string _codice, string _localita, string _note, int? _dipendenti, IList<ClienteDto> _clientes, IList<SocioDto> _socios, IList<AnagraficaClienteDto> _anagraficaClientes, IList<AccountDto> _accounts)
		{
			this.Id = _id;
			this.RagioneSociale = _ragioneSociale;
			this.Indirizzo = _indirizzo;
			this.CAP = _cAP;
			this.Comune = _comune;
			this.Provincia = _provincia;
			this.PartitaIva = _partitaIva;
			this.Telefono = _telefono;
			this.Fax = _fax;
			this.Email = _email;
			this.CodiceCatastale = _codiceCatastale;
			this.PEC = _pEC;
			this.Codice = _codice;
			this.Localita = _localita;
			this.Note = _note;
			this.Dipendenti = _dipendenti;
			this.Clientes = _clientes;
			this.Socios = _socios;
			this.AnagraficaClientes = _anagraficaClientes;
			this.Accounts = _accounts;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string RagioneSociale { get;set; }

		[DataMember]
		public virtual string Indirizzo { get;set; }

		[DataMember]
		public virtual string CAP { get;set; }

		[DataMember]
		public virtual string Comune { get;set; }

		[DataMember]
		public virtual string Provincia { get;set; }

		[DataMember]
		public virtual string PartitaIva { get;set; }

		[DataMember]
		public virtual string Telefono { get;set; }

		[DataMember]
		public virtual string Fax { get;set; }

		[DataMember]
		public virtual string Email { get;set; }

		[DataMember]
		public virtual string CodiceCatastale { get;set; }

		[DataMember]
		public virtual string PEC { get;set; }

		[DataMember]
		public virtual string Codice { get;set; }

		[DataMember]
		public virtual string Localita { get;set; }

		[DataMember]
		public virtual string Note { get;set; }

		[DataMember]
		public virtual int? Dipendenti { get;set; }

		[DataMember]
		public virtual IList<ClienteDto> Clientes { get;set; }

		[DataMember]
		public virtual IList<SocioDto> Socios { get;set; }

		[DataMember]
		public virtual IList<AnagraficaClienteDto> AnagraficaClientes { get;set; }

		[DataMember]
		public virtual IList<AccountDto> Accounts { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(AnagraficaClienteDto))]
	[KnownType(typeof(AnagraficaPADto))]
	[KnownType(typeof(AziendaDto))]
	[KnownType(typeof(FatturaDto))]
	public partial class ClienteDto : IDtoWithKey
	{
		public ClienteDto()
		{
		}
		
		public ClienteDto(int _id, int _aziendaId, int _anagraficaClienteId, int _anagraficaPAId, string _tipo, AnagraficaClienteDto _anagraficaCliente, AnagraficaPADto _anagraficaPA, AziendaDto _azienda, IList<FatturaDto> _fatturas)
		{
			this.Id = _id;
			this.AziendaId = _aziendaId;
			this.AnagraficaClienteId = _anagraficaClienteId;
			this.AnagraficaPAId = _anagraficaPAId;
			this.Tipo = _tipo;
			this.AnagraficaCliente = _anagraficaCliente;
			this.AnagraficaPA = _anagraficaPA;
			this.Azienda = _azienda;
			this.Fatturas = _fatturas;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int AziendaId { get;set; }

		[DataMember]
		public virtual int AnagraficaClienteId { get;set; }

		[DataMember]
		public virtual int AnagraficaPAId { get;set; }

		[DataMember]
		public virtual string Tipo { get;set; }

		[DataMember]
		public virtual AnagraficaClienteDto AnagraficaCliente { get;set; }

		[DataMember]
		public virtual AnagraficaPADto AnagraficaPA { get;set; }

		[DataMember]
		public virtual AziendaDto Azienda { get;set; }

		[DataMember]
		public virtual IList<FatturaDto> Fatturas { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ClienteDto))]
	[KnownType(typeof(TrasmissioneDto))]
	[KnownType(typeof(IncassoDto))]
	[KnownType(typeof(FatturaElettronicaBodyDto))]
	[KnownType(typeof(FatturaElettronicaHeaderDto))]
	public partial class FatturaDto : IDtoWithKey
	{
		public FatturaDto()
		{
		}
		
		public FatturaDto(int _id, int _clienteId, ClienteDto _cliente, IList<TrasmissioneDto> _trasmissiones, IList<IncassoDto> _incassos, IList<FatturaElettronicaBodyDto> _fatturaElettronicaBodies, FatturaElettronicaHeaderDto _fatturaElettronicaHeader)
		{
			this.Id = _id;
			this.ClienteId = _clienteId;
			this.Cliente = _cliente;
			this.Trasmissiones = _trasmissiones;
			this.Incassos = _incassos;
			this.FatturaElettronicaBodies = _fatturaElettronicaBodies;
			this.FatturaElettronicaHeader = _fatturaElettronicaHeader;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int ClienteId { get;set; }

		[DataMember]
		public virtual ClienteDto Cliente { get;set; }

		[DataMember]
		public virtual IList<TrasmissioneDto> Trasmissiones { get;set; }

		[DataMember]
		public virtual IList<IncassoDto> Incassos { get;set; }

		[DataMember]
		public virtual IList<FatturaElettronicaBodyDto> FatturaElettronicaBodies { get;set; }

		[DataMember]
		public virtual FatturaElettronicaHeaderDto FatturaElettronicaHeader { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(FatturaDto))]
	public partial class TrasmissioneDto : IDtoWithKey
	{
		public TrasmissioneDto()
		{
		}
		
		public TrasmissioneDto(int _id, int _fatturaId, FatturaDto _fattura)
		{
			this.Id = _id;
			this.FatturaId = _fatturaId;
			this.Fattura = _fattura;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int FatturaId { get;set; }

		[DataMember]
		public virtual FatturaDto Fattura { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(AziendaDto))]
	[KnownType(typeof(ClienteDto))]
	public partial class AnagraficaClienteDto : IDtoWithKey
	{
		public AnagraficaClienteDto()
		{
		}
		
		public AnagraficaClienteDto(int _id, int _aziendaId, string _ragioneSociale, string _cognome, string _codice, AziendaDto _azienda, IList<ClienteDto> _clientes)
		{
			this.Id = _id;
			this.AziendaId = _aziendaId;
			this.RagioneSociale = _ragioneSociale;
			this.Cognome = _cognome;
			this.Codice = _codice;
			this.Azienda = _azienda;
			this.Clientes = _clientes;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int AziendaId { get;set; }

		[DataMember]
		public virtual string RagioneSociale { get;set; }

		[DataMember]
		public virtual string Cognome { get;set; }

		[DataMember]
		public virtual string Codice { get;set; }

		[DataMember]
		public virtual AziendaDto Azienda { get;set; }

		[DataMember]
		public virtual IList<ClienteDto> Clientes { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(FatturaDto))]
	public partial class IncassoDto : IDtoWithKey
	{
		public IncassoDto()
		{
		}
		
		public IncassoDto(int _id, int _fatturaId, FatturaDto _fattura)
		{
			this.Id = _id;
			this.FatturaId = _fatturaId;
			this.Fattura = _fattura;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int FatturaId { get;set; }

		[DataMember]
		public virtual FatturaDto Fattura { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(AziendaDto))]
	public partial class SocioDto : IDtoWithKey
	{
		public SocioDto()
		{
		}
		
		public SocioDto(int _id, int _aziendaId, string _cognome, string _nome, string _tipoCarica, AziendaDto _azienda)
		{
			this.Id = _id;
			this.AziendaId = _aziendaId;
			this.Cognome = _cognome;
			this.Nome = _nome;
			this.TipoCarica = _tipoCarica;
			this.Azienda = _azienda;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int AziendaId { get;set; }

		[DataMember]
		public virtual string Cognome { get;set; }

		[DataMember]
		public virtual string Nome { get;set; }

		[DataMember]
		public virtual string TipoCarica { get;set; }

		[DataMember]
		public virtual AziendaDto Azienda { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ClienteDto))]
	public partial class AnagraficaPADto : IDtoWithKey
	{
		public AnagraficaPADto()
		{
		}
		
		public AnagraficaPADto(int _id, string _codice, string _denominazione, string _comune, string _nomeResponsabile, string _cognomeResponsabile, int _cAP, string _provincia, string _regione, string _sitoIstituzionale, string _indirizzo, string _titoloResponsabile, string _tipologiaIstat, string _tipologiaAmministrazione, string _acronimo, bool _cfValidato, string _codiceFiscale, string _email, IList<ClienteDto> _clientes)
		{
			this.Id = _id;
			this.Codice = _codice;
			this.Denominazione = _denominazione;
			this.Comune = _comune;
			this.NomeResponsabile = _nomeResponsabile;
			this.CognomeResponsabile = _cognomeResponsabile;
			this.CAP = _cAP;
			this.Provincia = _provincia;
			this.Regione = _regione;
			this.SitoIstituzionale = _sitoIstituzionale;
			this.Indirizzo = _indirizzo;
			this.TitoloResponsabile = _titoloResponsabile;
			this.TipologiaIstat = _tipologiaIstat;
			this.TipologiaAmministrazione = _tipologiaAmministrazione;
			this.Acronimo = _acronimo;
			this.CfValidato = _cfValidato;
			this.CodiceFiscale = _codiceFiscale;
			this.Email = _email;
			this.Clientes = _clientes;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string Codice { get;set; }

		[DataMember]
		public virtual string Denominazione { get;set; }

		[DataMember]
		public virtual string Comune { get;set; }

		[DataMember]
		public virtual string NomeResponsabile { get;set; }

		[DataMember]
		public virtual string CognomeResponsabile { get;set; }

		[DataMember]
		public virtual int CAP { get;set; }

		[DataMember]
		public virtual string Provincia { get;set; }

		[DataMember]
		public virtual string Regione { get;set; }

		[DataMember]
		public virtual string SitoIstituzionale { get;set; }

		[DataMember]
		public virtual string Indirizzo { get;set; }

		[DataMember]
		public virtual string TitoloResponsabile { get;set; }

		[DataMember]
		public virtual string TipologiaIstat { get;set; }

		[DataMember]
		public virtual string TipologiaAmministrazione { get;set; }

		[DataMember]
		public virtual string Acronimo { get;set; }

		[DataMember]
		public virtual bool CfValidato { get;set; }

		[DataMember]
		public virtual string CodiceFiscale { get;set; }

		[DataMember]
		public virtual string Email { get;set; }

		[DataMember]
		public virtual IList<ClienteDto> Clientes { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(FatturaDto))]
	[KnownType(typeof(DatiTrasmissioneDto))]
	[KnownType(typeof(CedentePrestatoreDto))]
	[KnownType(typeof(CessionarioCommittenteDto))]
	public partial class FatturaElettronicaHeaderDto : IDtoWithKey
	{
		public FatturaElettronicaHeaderDto()
		{
		}
		
		public FatturaElettronicaHeaderDto(int _id, FatturaDto _fattura, DatiTrasmissioneDto _datiTrasmissione, CedentePrestatoreDto _cedentePrestatore, CessionarioCommittenteDto _cessionarioCommittente)
		{
			this.Id = _id;
			this.Fattura = _fattura;
			this.DatiTrasmissione = _datiTrasmissione;
			this.CedentePrestatore = _cedentePrestatore;
			this.CessionarioCommittente = _cessionarioCommittente;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual FatturaDto Fattura { get;set; }

		[DataMember]
		public virtual DatiTrasmissioneDto DatiTrasmissione { get;set; }

		[DataMember]
		public virtual CedentePrestatoreDto CedentePrestatore { get;set; }

		[DataMember]
		public virtual CessionarioCommittenteDto CessionarioCommittente { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(FatturaDto))]
	[KnownType(typeof(DatiPagamentoDto))]
	[KnownType(typeof(AllegatiDto))]
	[KnownType(typeof(DatiGeneraliDto))]
	public partial class FatturaElettronicaBodyDto : IDtoWithKey
	{
		public FatturaElettronicaBodyDto()
		{
		}
		
		public FatturaElettronicaBodyDto(int _id, int _fatturaId, FatturaDto _fattura, IList<DatiPagamentoDto> _datiPagamentos, IList<AllegatiDto> _allegatis, DatiGeneraliDto _datiGenerali)
		{
			this.Id = _id;
			this.FatturaId = _fatturaId;
			this.Fattura = _fattura;
			this.DatiPagamentos = _datiPagamentos;
			this.Allegatis = _allegatis;
			this.DatiGenerali = _datiGenerali;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int FatturaId { get;set; }

		[DataMember]
		public virtual FatturaDto Fattura { get;set; }

		[DataMember]
		public virtual IList<DatiPagamentoDto> DatiPagamentos { get;set; }

		[DataMember]
		public virtual IList<AllegatiDto> Allegatis { get;set; }

		[DataMember]
		public virtual DatiGeneraliDto DatiGenerali { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(FatturaElettronicaHeaderDto))]
	[KnownType(typeof(IdFiscaleDto))]
	[KnownType(typeof(ContattiDto))]
	public partial class DatiTrasmissioneDto : IDtoWithKey
	{
		public DatiTrasmissioneDto()
		{
		}
		
		public DatiTrasmissioneDto(int _id, string _progressivoInvio, string _formatoTrasmissione, string _codiceDestinatario, FatturaElettronicaHeaderDto _fatturaElettronicaHeader, IList<IdFiscaleDto> _idFiscales, IList<ContattiDto> _contattis)
		{
			this.Id = _id;
			this.ProgressivoInvio = _progressivoInvio;
			this.FormatoTrasmissione = _formatoTrasmissione;
			this.CodiceDestinatario = _codiceDestinatario;
			this.FatturaElettronicaHeader = _fatturaElettronicaHeader;
			this.IdFiscales = _idFiscales;
			this.Contattis = _contattis;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string ProgressivoInvio { get;set; }

		[DataMember]
		public virtual string FormatoTrasmissione { get;set; }

		[DataMember]
		public virtual string CodiceDestinatario { get;set; }

		[DataMember]
		public virtual FatturaElettronicaHeaderDto FatturaElettronicaHeader { get;set; }

		[DataMember]
		public virtual IList<IdFiscaleDto> IdFiscales { get;set; }

		[DataMember]
		public virtual IList<ContattiDto> Contattis { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(DatiTrasmissioneDto))]
	[KnownType(typeof(DatiAnagraficiCedenteDto))]
	public partial class IdFiscaleDto : IDtoWithKey
	{
		public IdFiscaleDto()
		{
		}
		
		public IdFiscaleDto(int _id, string _idPaese, string _idCodice, int _idTrasmittente, int _idFiscaleIVA, DatiTrasmissioneDto _datiTrasmissione, DatiAnagraficiCedenteDto _datiAnagraficiCedente)
		{
			this.Id = _id;
			this.IdPaese = _idPaese;
			this.IdCodice = _idCodice;
			this.IdTrasmittente = _idTrasmittente;
			this.IdFiscaleIVA = _idFiscaleIVA;
			this.DatiTrasmissione = _datiTrasmissione;
			this.DatiAnagraficiCedente = _datiAnagraficiCedente;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string IdPaese { get;set; }

		[DataMember]
		public virtual string IdCodice { get;set; }

		[DataMember]
		public virtual int IdTrasmittente { get;set; }

		[DataMember]
		public virtual int IdFiscaleIVA { get;set; }

		[DataMember]
		public virtual DatiTrasmissioneDto DatiTrasmissione { get;set; }

		[DataMember]
		public virtual DatiAnagraficiCedenteDto DatiAnagraficiCedente { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(DatiTrasmissioneDto))]
	[KnownType(typeof(CedentePrestatoreDto))]
	public partial class ContattiDto : IDtoWithKey
	{
		public ContattiDto()
		{
		}
		
		public ContattiDto(int _id, string _telefono, string _email, int _trasmittenteId, int _cedentePrestatoreId, DatiTrasmissioneDto _datiTrasmissione, CedentePrestatoreDto _cedentePrestatore)
		{
			this.Id = _id;
			this.Telefono = _telefono;
			this.Email = _email;
			this.TrasmittenteId = _trasmittenteId;
			this.CedentePrestatoreId = _cedentePrestatoreId;
			this.DatiTrasmissione = _datiTrasmissione;
			this.CedentePrestatore = _cedentePrestatore;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string Telefono { get;set; }

		[DataMember]
		public virtual string Email { get;set; }

		[DataMember]
		public virtual int TrasmittenteId { get;set; }

		[DataMember]
		public virtual int CedentePrestatoreId { get;set; }

		[DataMember]
		public virtual DatiTrasmissioneDto DatiTrasmissione { get;set; }

		[DataMember]
		public virtual CedentePrestatoreDto CedentePrestatore { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(FatturaElettronicaHeaderDto))]
	[KnownType(typeof(IndirizzoDto))]
	[KnownType(typeof(ContattiDto))]
	[KnownType(typeof(DatiAnagraficiCedenteDto))]
	public partial class CedentePrestatoreDto : IDtoWithKey
	{
		public CedentePrestatoreDto()
		{
		}
		
		public CedentePrestatoreDto(int _id, string _riferimentoAmministrazione, FatturaElettronicaHeaderDto _fatturaElettronicaHeader, IList<IndirizzoDto> _indirizzos, IList<ContattiDto> _contattis, IList<DatiAnagraficiCedenteDto> _datiAnagraficiCedentes)
		{
			this.Id = _id;
			this.RiferimentoAmministrazione = _riferimentoAmministrazione;
			this.FatturaElettronicaHeader = _fatturaElettronicaHeader;
			this.Indirizzos = _indirizzos;
			this.Contattis = _contattis;
			this.DatiAnagraficiCedentes = _datiAnagraficiCedentes;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string RiferimentoAmministrazione { get;set; }

		[DataMember]
		public virtual FatturaElettronicaHeaderDto FatturaElettronicaHeader { get;set; }

		[DataMember]
		public virtual IList<IndirizzoDto> Indirizzos { get;set; }

		[DataMember]
		public virtual IList<ContattiDto> Contattis { get;set; }

		[DataMember]
		public virtual IList<DatiAnagraficiCedenteDto> DatiAnagraficiCedentes { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(CedentePrestatoreDto))]
	[KnownType(typeof(CessionarioCommittenteDto))]
	[KnownType(typeof(IdFiscaleDto))]
	[KnownType(typeof(AnagraficaDto))]
	public partial class DatiAnagraficiCedenteDto : IDtoWithKey
	{
		public DatiAnagraficiCedenteDto()
		{
		}
		
		public DatiAnagraficiCedenteDto(int _id, string _codiceFiscale, string _alboProfessionale, string _provinciaAlbo, string _numeroIscrizioneAlbo, DateTime _dataIscrizioneAlbo, string _regimeFiscale, int _cedentePrestatoreId, int _cessionarioCommittenteId, CedentePrestatoreDto _cedentePrestatore, CessionarioCommittenteDto _cessionarioCommittente, IList<IdFiscaleDto> _idFiscales, AnagraficaDto _anagrafica)
		{
			this.Id = _id;
			this.CodiceFiscale = _codiceFiscale;
			this.AlboProfessionale = _alboProfessionale;
			this.ProvinciaAlbo = _provinciaAlbo;
			this.NumeroIscrizioneAlbo = _numeroIscrizioneAlbo;
			this.DataIscrizioneAlbo = _dataIscrizioneAlbo;
			this.RegimeFiscale = _regimeFiscale;
			this.CedentePrestatoreId = _cedentePrestatoreId;
			this.CessionarioCommittenteId = _cessionarioCommittenteId;
			this.CedentePrestatore = _cedentePrestatore;
			this.CessionarioCommittente = _cessionarioCommittente;
			this.IdFiscales = _idFiscales;
			this.Anagrafica = _anagrafica;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string CodiceFiscale { get;set; }

		[DataMember]
		public virtual string AlboProfessionale { get;set; }

		[DataMember]
		public virtual string ProvinciaAlbo { get;set; }

		[DataMember]
		public virtual string NumeroIscrizioneAlbo { get;set; }

		[DataMember]
		public virtual DateTime DataIscrizioneAlbo { get;set; }

		[DataMember]
		public virtual string RegimeFiscale { get;set; }

		[DataMember]
		public virtual int CedentePrestatoreId { get;set; }

		[DataMember]
		public virtual int CessionarioCommittenteId { get;set; }

		[DataMember]
		public virtual CedentePrestatoreDto CedentePrestatore { get;set; }

		[DataMember]
		public virtual CessionarioCommittenteDto CessionarioCommittente { get;set; }

		[DataMember]
		public virtual IList<IdFiscaleDto> IdFiscales { get;set; }

		[DataMember]
		public virtual AnagraficaDto Anagrafica { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(DatiAnagraficiCedenteDto))]
	public partial class AnagraficaDto : IDtoWithKey
	{
		public AnagraficaDto()
		{
		}
		
		public AnagraficaDto(int _id, string _denominazione, string _nome, string _cognome, string _titolo, string _codEORI, DatiAnagraficiCedenteDto _datiAnagraficiCedente)
		{
			this.Id = _id;
			this.Denominazione = _denominazione;
			this.Nome = _nome;
			this.Cognome = _cognome;
			this.Titolo = _titolo;
			this.CodEORI = _codEORI;
			this.DatiAnagraficiCedente = _datiAnagraficiCedente;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string Denominazione { get;set; }

		[DataMember]
		public virtual string Nome { get;set; }

		[DataMember]
		public virtual string Cognome { get;set; }

		[DataMember]
		public virtual string Titolo { get;set; }

		[DataMember]
		public virtual string CodEORI { get;set; }

		[DataMember]
		public virtual DatiAnagraficiCedenteDto DatiAnagraficiCedente { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(CedentePrestatoreDto))]
	[KnownType(typeof(CessionarioCommittenteDto))]
	public partial class IndirizzoDto : IDtoWithKey
	{
		public IndirizzoDto()
		{
		}
		
		public IndirizzoDto(int _id, string __indirizzo, string _numeroCivico, string _cAP, string _comune, string _provincia, string _nazione, int _cedentePrestatoreId, int _cessionarioCommittenteId, CedentePrestatoreDto _cedentePrestatore, CessionarioCommittenteDto _cessionarioCommittente)
		{
			this.Id = _id;
			this._Indirizzo = __indirizzo;
			this.NumeroCivico = _numeroCivico;
			this.CAP = _cAP;
			this.Comune = _comune;
			this.Provincia = _provincia;
			this.Nazione = _nazione;
			this.CedentePrestatoreId = _cedentePrestatoreId;
			this.CessionarioCommittenteId = _cessionarioCommittenteId;
			this.CedentePrestatore = _cedentePrestatore;
			this.CessionarioCommittente = _cessionarioCommittente;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string _Indirizzo { get;set; }

		[DataMember]
		public virtual string NumeroCivico { get;set; }

		[DataMember]
		public virtual string CAP { get;set; }

		[DataMember]
		public virtual string Comune { get;set; }

		[DataMember]
		public virtual string Provincia { get;set; }

		[DataMember]
		public virtual string Nazione { get;set; }

		[DataMember]
		public virtual int CedentePrestatoreId { get;set; }

		[DataMember]
		public virtual int CessionarioCommittenteId { get;set; }

		[DataMember]
		public virtual CedentePrestatoreDto CedentePrestatore { get;set; }

		[DataMember]
		public virtual CessionarioCommittenteDto CessionarioCommittente { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(AziendaDto))]
	public partial class AccountDto : IDtoWithKey
	{
		public AccountDto()
		{
		}
		
		public AccountDto(int _id, int _aziendaId, string _username, string _password, string _nickname, string _ruolo, string _note, DateTime? _creazione, bool? _abilitato, AziendaDto _azienda)
		{
			this.Id = _id;
			this.AziendaId = _aziendaId;
			this.Username = _username;
			this.Password = _password;
			this.Nickname = _nickname;
			this.Ruolo = _ruolo;
			this.Note = _note;
			this.Creazione = _creazione;
			this.Abilitato = _abilitato;
			this.Azienda = _azienda;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int AziendaId { get;set; }

		[DataMember]
		public virtual string Username { get;set; }

		[DataMember]
		public virtual string Password { get;set; }

		[DataMember]
		public virtual string Nickname { get;set; }

		[DataMember]
		public virtual string Ruolo { get;set; }

		[DataMember]
		public virtual string Note { get;set; }

		[DataMember]
		public virtual DateTime? Creazione { get;set; }

		[DataMember]
		public virtual bool? Abilitato { get;set; }

		[DataMember]
		public virtual AziendaDto Azienda { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(FatturaElettronicaHeaderDto))]
	[KnownType(typeof(DatiAnagraficiCedenteDto))]
	[KnownType(typeof(IndirizzoDto))]
	public partial class CessionarioCommittenteDto : IDtoWithKey
	{
		public CessionarioCommittenteDto()
		{
		}
		
		public CessionarioCommittenteDto(int _id, FatturaElettronicaHeaderDto _fatturaElettronicaHeader, IList<DatiAnagraficiCedenteDto> _datiAnagraficiCedentes, IList<IndirizzoDto> _indirizzos)
		{
			this.Id = _id;
			this.FatturaElettronicaHeader = _fatturaElettronicaHeader;
			this.DatiAnagraficiCedentes = _datiAnagraficiCedentes;
			this.Indirizzos = _indirizzos;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual FatturaElettronicaHeaderDto FatturaElettronicaHeader { get;set; }

		[DataMember]
		public virtual IList<DatiAnagraficiCedenteDto> DatiAnagraficiCedentes { get;set; }

		[DataMember]
		public virtual IList<IndirizzoDto> Indirizzos { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(FatturaElettronicaBodyDto))]
	[KnownType(typeof(DatiGeneraliDocumentoDto))]
	[KnownType(typeof(DatiBeniServiziDto))]
	public partial class DatiGeneraliDto : IDtoWithKey
	{
		public DatiGeneraliDto()
		{
		}
		
		public DatiGeneraliDto(int _id, FatturaElettronicaBodyDto _fatturaElettronicaBody, DatiGeneraliDocumentoDto _datiGeneraliDocumento, DatiBeniServiziDto _datiBeniServizi)
		{
			this.Id = _id;
			this.FatturaElettronicaBody = _fatturaElettronicaBody;
			this.DatiGeneraliDocumento = _datiGeneraliDocumento;
			this.DatiBeniServizi = _datiBeniServizi;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual FatturaElettronicaBodyDto FatturaElettronicaBody { get;set; }

		[DataMember]
		public virtual DatiGeneraliDocumentoDto DatiGeneraliDocumento { get;set; }

		[DataMember]
		public virtual DatiBeniServiziDto DatiBeniServizi { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(DatiGeneraliDto))]
	[KnownType(typeof(DatiRitenutaDto))]
	public partial class DatiGeneraliDocumentoDto : IDtoWithKey
	{
		public DatiGeneraliDocumentoDto()
		{
		}
		
		public DatiGeneraliDocumentoDto(int _id, string _tipoDocumento, string _divisa, DateTime _data, string _numero, decimal _importotTotaleDocumento, decimal _arrotondamento, string _causale, DatiGeneraliDto _datiGenerali, DatiRitenutaDto _datiRitenuta)
		{
			this.Id = _id;
			this.TipoDocumento = _tipoDocumento;
			this.Divisa = _divisa;
			this.Data = _data;
			this.Numero = _numero;
			this.ImportotTotaleDocumento = _importotTotaleDocumento;
			this.Arrotondamento = _arrotondamento;
			this.Causale = _causale;
			this.DatiGenerali = _datiGenerali;
			this.DatiRitenuta = _datiRitenuta;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string TipoDocumento { get;set; }

		[DataMember]
		public virtual string Divisa { get;set; }

		[DataMember]
		public virtual DateTime Data { get;set; }

		[DataMember]
		public virtual string Numero { get;set; }

		[DataMember]
		public virtual decimal ImportotTotaleDocumento { get;set; }

		[DataMember]
		public virtual decimal Arrotondamento { get;set; }

		[DataMember]
		public virtual string Causale { get;set; }

		[DataMember]
		public virtual DatiGeneraliDto DatiGenerali { get;set; }

		[DataMember]
		public virtual DatiRitenutaDto DatiRitenuta { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(DatiGeneraliDocumentoDto))]
	public partial class DatiRitenutaDto : IDtoWithKey
	{
		public DatiRitenutaDto()
		{
		}
		
		public DatiRitenutaDto(int _id, string _tipoRitenuta, decimal _importoRitenuta, decimal _aliquotaRitenuta, string _causalePAgamento, DatiGeneraliDocumentoDto _datiGeneraliDocumento)
		{
			this.Id = _id;
			this.TipoRitenuta = _tipoRitenuta;
			this.ImportoRitenuta = _importoRitenuta;
			this.AliquotaRitenuta = _aliquotaRitenuta;
			this.CausalePAgamento = _causalePAgamento;
			this.DatiGeneraliDocumento = _datiGeneraliDocumento;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string TipoRitenuta { get;set; }

		[DataMember]
		public virtual decimal ImportoRitenuta { get;set; }

		[DataMember]
		public virtual decimal AliquotaRitenuta { get;set; }

		[DataMember]
		public virtual string CausalePAgamento { get;set; }

		[DataMember]
		public virtual DatiGeneraliDocumentoDto DatiGeneraliDocumento { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(DatiGeneraliDto))]
	[KnownType(typeof(DettaglioLineeDto))]
	[KnownType(typeof(DatiRiepilogoDto))]
	public partial class DatiBeniServiziDto : IDtoWithKey
	{
		public DatiBeniServiziDto()
		{
		}
		
		public DatiBeniServiziDto(int _id, DatiGeneraliDto _datiGenerali, IList<DettaglioLineeDto> _dettaglioLinees, IList<DatiRiepilogoDto> _datiRiepilogos)
		{
			this.Id = _id;
			this.DatiGenerali = _datiGenerali;
			this.DettaglioLinees = _dettaglioLinees;
			this.DatiRiepilogos = _datiRiepilogos;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual DatiGeneraliDto DatiGenerali { get;set; }

		[DataMember]
		public virtual IList<DettaglioLineeDto> DettaglioLinees { get;set; }

		[DataMember]
		public virtual IList<DatiRiepilogoDto> DatiRiepilogos { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(DatiBeniServiziDto))]
	public partial class DettaglioLineeDto : IDtoWithKey
	{
		public DettaglioLineeDto()
		{
		}
		
		public DettaglioLineeDto(int _id, int _datiBeniServiziId, string _numeroLinea, string _descrizione, decimal _prezzoUnitario, decimal _prezzoTotale, decimal _aliquotaIVA, string _ritenuta, DateTime _dataInizioPeriodo, DateTime _dataFinePeriodo, DatiBeniServiziDto _datiBeniServizi)
		{
			this.Id = _id;
			this.DatiBeniServiziId = _datiBeniServiziId;
			this.NumeroLinea = _numeroLinea;
			this.Descrizione = _descrizione;
			this.PrezzoUnitario = _prezzoUnitario;
			this.PrezzoTotale = _prezzoTotale;
			this.AliquotaIVA = _aliquotaIVA;
			this.Ritenuta = _ritenuta;
			this.DataInizioPeriodo = _dataInizioPeriodo;
			this.DataFinePeriodo = _dataFinePeriodo;
			this.DatiBeniServizi = _datiBeniServizi;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int DatiBeniServiziId { get;set; }

		[DataMember]
		public virtual string NumeroLinea { get;set; }

		[DataMember]
		public virtual string Descrizione { get;set; }

		[DataMember]
		public virtual decimal PrezzoUnitario { get;set; }

		[DataMember]
		public virtual decimal PrezzoTotale { get;set; }

		[DataMember]
		public virtual decimal AliquotaIVA { get;set; }

		[DataMember]
		public virtual string Ritenuta { get;set; }

		[DataMember]
		public virtual DateTime DataInizioPeriodo { get;set; }

		[DataMember]
		public virtual DateTime DataFinePeriodo { get;set; }

		[DataMember]
		public virtual DatiBeniServiziDto DatiBeniServizi { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(DatiBeniServiziDto))]
	public partial class DatiRiepilogoDto : IDtoWithKey
	{
		public DatiRiepilogoDto()
		{
		}
		
		public DatiRiepilogoDto(int _id, int _datiBeniServiziId, decimal _aliquotaIVA, decimal _imponibileImporto, decimal _imposta, DatiBeniServiziDto _datiBeniServizi)
		{
			this.Id = _id;
			this.DatiBeniServiziId = _datiBeniServiziId;
			this.AliquotaIVA = _aliquotaIVA;
			this.ImponibileImporto = _imponibileImporto;
			this.Imposta = _imposta;
			this.DatiBeniServizi = _datiBeniServizi;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int DatiBeniServiziId { get;set; }

		[DataMember]
		public virtual decimal AliquotaIVA { get;set; }

		[DataMember]
		public virtual decimal ImponibileImporto { get;set; }

		[DataMember]
		public virtual decimal Imposta { get;set; }

		[DataMember]
		public virtual DatiBeniServiziDto DatiBeniServizi { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(FatturaElettronicaBodyDto))]
	[KnownType(typeof(DettaglioPagamentoDto))]
	public partial class DatiPagamentoDto : IDtoWithKey
	{
		public DatiPagamentoDto()
		{
		}
		
		public DatiPagamentoDto(int _id, int _fatturaElettronicaBodyId, string _condizioniPagamento, FatturaElettronicaBodyDto _fatturaElettronicaBody, IList<DettaglioPagamentoDto> _dettaglioPagamentos)
		{
			this.Id = _id;
			this.FatturaElettronicaBodyId = _fatturaElettronicaBodyId;
			this.CondizioniPagamento = _condizioniPagamento;
			this.FatturaElettronicaBody = _fatturaElettronicaBody;
			this.DettaglioPagamentos = _dettaglioPagamentos;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int FatturaElettronicaBodyId { get;set; }

		[DataMember]
		public virtual string CondizioniPagamento { get;set; }

		[DataMember]
		public virtual FatturaElettronicaBodyDto FatturaElettronicaBody { get;set; }

		[DataMember]
		public virtual IList<DettaglioPagamentoDto> DettaglioPagamentos { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(DatiPagamentoDto))]
	public partial class DettaglioPagamentoDto : IDtoWithKey
	{
		public DettaglioPagamentoDto()
		{
		}
		
		public DettaglioPagamentoDto(int _id, int _datiPagamentoId, string _beneficiario, string _modalitaPagamento, DateTime _dataRiferimentoTerminiPagamento, int _giorniTerminiPagamento, decimal _dataScadenzaPagamento, string _importoPagamento, string _istitutoFinanziario, string _iBAN, string _aBI, string _cAB, string _bIC, DateTime _dataDecorrenzaPenale, string _codUfficioPostale, string _cognomeQuietanzante, string _nomeQuietanzante, string _cFQuietanzante, string _titoloQuietanzante, decimal _scontoPagamentoAnticipato, DateTime _dataLimitePagamentoAnticipato, decimal _penalitaPagamentiRitardati, string _codicePagamento, DatiPagamentoDto _datiPagamento)
		{
			this.Id = _id;
			this.DatiPagamentoId = _datiPagamentoId;
			this.Beneficiario = _beneficiario;
			this.ModalitaPagamento = _modalitaPagamento;
			this.DataRiferimentoTerminiPagamento = _dataRiferimentoTerminiPagamento;
			this.GiorniTerminiPagamento = _giorniTerminiPagamento;
			this.DataScadenzaPagamento = _dataScadenzaPagamento;
			this.ImportoPagamento = _importoPagamento;
			this.IstitutoFinanziario = _istitutoFinanziario;
			this.IBAN = _iBAN;
			this.ABI = _aBI;
			this.CAB = _cAB;
			this.BIC = _bIC;
			this.DataDecorrenzaPenale = _dataDecorrenzaPenale;
			this.CodUfficioPostale = _codUfficioPostale;
			this.CognomeQuietanzante = _cognomeQuietanzante;
			this.NomeQuietanzante = _nomeQuietanzante;
			this.CFQuietanzante = _cFQuietanzante;
			this.TitoloQuietanzante = _titoloQuietanzante;
			this.ScontoPagamentoAnticipato = _scontoPagamentoAnticipato;
			this.DataLimitePagamentoAnticipato = _dataLimitePagamentoAnticipato;
			this.PenalitaPagamentiRitardati = _penalitaPagamentiRitardati;
			this.CodicePagamento = _codicePagamento;
			this.DatiPagamento = _datiPagamento;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int DatiPagamentoId { get;set; }

		[DataMember]
		public virtual string Beneficiario { get;set; }

		[DataMember]
		public virtual string ModalitaPagamento { get;set; }

		[DataMember]
		public virtual DateTime DataRiferimentoTerminiPagamento { get;set; }

		[DataMember]
		public virtual int GiorniTerminiPagamento { get;set; }

		[DataMember]
		public virtual decimal DataScadenzaPagamento { get;set; }

		[DataMember]
		public virtual string ImportoPagamento { get;set; }

		[DataMember]
		public virtual string IstitutoFinanziario { get;set; }

		[DataMember]
		public virtual string IBAN { get;set; }

		[DataMember]
		public virtual string ABI { get;set; }

		[DataMember]
		public virtual string CAB { get;set; }

		[DataMember]
		public virtual string BIC { get;set; }

		[DataMember]
		public virtual DateTime DataDecorrenzaPenale { get;set; }

		[DataMember]
		public virtual string CodUfficioPostale { get;set; }

		[DataMember]
		public virtual string CognomeQuietanzante { get;set; }

		[DataMember]
		public virtual string NomeQuietanzante { get;set; }

		[DataMember]
		public virtual string CFQuietanzante { get;set; }

		[DataMember]
		public virtual string TitoloQuietanzante { get;set; }

		[DataMember]
		public virtual decimal ScontoPagamentoAnticipato { get;set; }

		[DataMember]
		public virtual DateTime DataLimitePagamentoAnticipato { get;set; }

		[DataMember]
		public virtual decimal PenalitaPagamentiRitardati { get;set; }

		[DataMember]
		public virtual string CodicePagamento { get;set; }

		[DataMember]
		public virtual DatiPagamentoDto DatiPagamento { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(FatturaElettronicaBodyDto))]
	public partial class AllegatiDto : IDtoWithKey
	{
		public AllegatiDto()
		{
		}
		
		public AllegatiDto(int _id, string _nomeAttachment, string _algoritmoCompressione, string _formatoAttachment, string _descrizioneAttachment, Object _attachment, int _fatturaElettronicaBodyId, FatturaElettronicaBodyDto _fatturaElettronicaBody)
		{
			this.Id = _id;
			this.NomeAttachment = _nomeAttachment;
			this.AlgoritmoCompressione = _algoritmoCompressione;
			this.FormatoAttachment = _formatoAttachment;
			this.DescrizioneAttachment = _descrizioneAttachment;
			this.Attachment = _attachment;
			this.FatturaElettronicaBodyId = _fatturaElettronicaBodyId;
			this.FatturaElettronicaBody = _fatturaElettronicaBody;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string NomeAttachment { get;set; }

		[DataMember]
		public virtual string AlgoritmoCompressione { get;set; }

		[DataMember]
		public virtual string FormatoAttachment { get;set; }

		[DataMember]
		public virtual string DescrizioneAttachment { get;set; }

		[DataMember]
		public virtual Object Attachment { get;set; }

		[DataMember]
		public virtual int FatturaElettronicaBodyId { get;set; }

		[DataMember]
		public virtual FatturaElettronicaBodyDto FatturaElettronicaBody { get;set; }

	}
	
}
#pragma warning restore 1591
