#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Allegati
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _nomeAttachment;
		public virtual string NomeAttachment
		{
			get
			{
				return this._nomeAttachment;
			}
			set
			{
				this._nomeAttachment = value;
			}
		}
		
		private string _algoritmoCompressione;
		public virtual string AlgoritmoCompressione
		{
			get
			{
				return this._algoritmoCompressione;
			}
			set
			{
				this._algoritmoCompressione = value;
			}
		}
		
		private string _formatoAttachment;
		public virtual string FormatoAttachment
		{
			get
			{
				return this._formatoAttachment;
			}
			set
			{
				this._formatoAttachment = value;
			}
		}
		
		private string _descrizioneAttachment;
		public virtual string DescrizioneAttachment
		{
			get
			{
				return this._descrizioneAttachment;
			}
			set
			{
				this._descrizioneAttachment = value;
			}
		}
		
		private Object _attachment;
		public virtual Object Attachment
		{
			get
			{
				return this._attachment;
			}
			set
			{
				this._attachment = value;
			}
		}
		
		private int _fatturaElettronicaBodyId;
		public virtual int FatturaElettronicaBodyId
		{
			get
			{
				return this._fatturaElettronicaBodyId;
			}
			set
			{
				this._fatturaElettronicaBodyId = value;
			}
		}
		
		private FatturaElettronicaBody _fatturaElettronicaBody;
		public virtual FatturaElettronicaBody FatturaElettronicaBody
		{
			get
			{
				return this._fatturaElettronicaBody;
			}
			set
			{
				this._fatturaElettronicaBody = value;
			}
		}
		
	}
}
#pragma warning restore 1591
