#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class AnagraficaPA
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _codice;
		public virtual string Codice
		{
			get
			{
				return this._codice;
			}
			set
			{
				this._codice = value;
			}
		}
		
		private string _denominazione;
		public virtual string Denominazione
		{
			get
			{
				return this._denominazione;
			}
			set
			{
				this._denominazione = value;
			}
		}
		
		private string _comune;
		public virtual string Comune
		{
			get
			{
				return this._comune;
			}
			set
			{
				this._comune = value;
			}
		}
		
		private string _nomeResponsabile;
		public virtual string NomeResponsabile
		{
			get
			{
				return this._nomeResponsabile;
			}
			set
			{
				this._nomeResponsabile = value;
			}
		}
		
		private string _cognomeResponsabile;
		public virtual string CognomeResponsabile
		{
			get
			{
				return this._cognomeResponsabile;
			}
			set
			{
				this._cognomeResponsabile = value;
			}
		}
		
		private int _cAP;
		public virtual int CAP
		{
			get
			{
				return this._cAP;
			}
			set
			{
				this._cAP = value;
			}
		}
		
		private string _provincia;
		public virtual string Provincia
		{
			get
			{
				return this._provincia;
			}
			set
			{
				this._provincia = value;
			}
		}
		
		private string _regione;
		public virtual string Regione
		{
			get
			{
				return this._regione;
			}
			set
			{
				this._regione = value;
			}
		}
		
		private string _sitoIstituzionale;
		public virtual string SitoIstituzionale
		{
			get
			{
				return this._sitoIstituzionale;
			}
			set
			{
				this._sitoIstituzionale = value;
			}
		}
		
		private string _indirizzo;
		public virtual string Indirizzo
		{
			get
			{
				return this._indirizzo;
			}
			set
			{
				this._indirizzo = value;
			}
		}
		
		private string _titoloResponsabile;
		public virtual string TitoloResponsabile
		{
			get
			{
				return this._titoloResponsabile;
			}
			set
			{
				this._titoloResponsabile = value;
			}
		}
		
		private string _tipologiaIstat;
		public virtual string TipologiaIstat
		{
			get
			{
				return this._tipologiaIstat;
			}
			set
			{
				this._tipologiaIstat = value;
			}
		}
		
		private string _tipologiaAmministrazione;
		public virtual string TipologiaAmministrazione
		{
			get
			{
				return this._tipologiaAmministrazione;
			}
			set
			{
				this._tipologiaAmministrazione = value;
			}
		}
		
		private string _acronimo;
		public virtual string Acronimo
		{
			get
			{
				return this._acronimo;
			}
			set
			{
				this._acronimo = value;
			}
		}
		
		private bool _cfValidato;
		public virtual bool CfValidato
		{
			get
			{
				return this._cfValidato;
			}
			set
			{
				this._cfValidato = value;
			}
		}
		
		private string _codiceFiscale;
		public virtual string CodiceFiscale
		{
			get
			{
				return this._codiceFiscale;
			}
			set
			{
				this._codiceFiscale = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private IList<Cliente> _clientes = new List<Cliente>();
		public virtual IList<Cliente> Clientes
		{
			get
			{
				return this._clientes;
			}
		}
		
	}
}
#pragma warning restore 1591
