#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class CedentePrestatore
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _riferimentoAmministrazione;
		public virtual string RiferimentoAmministrazione
		{
			get
			{
				return this._riferimentoAmministrazione;
			}
			set
			{
				this._riferimentoAmministrazione = value;
			}
		}
		
		private FatturaElettronicaHeader _fatturaElettronicaHeader;
		public virtual FatturaElettronicaHeader FatturaElettronicaHeader
		{
			get
			{
				return this._fatturaElettronicaHeader;
			}
			set
			{
				this._fatturaElettronicaHeader = value;
			}
		}
		
		private DatiAnagraficiCedente _datiAnagraficiCedente;
		public virtual DatiAnagraficiCedente DatiAnagraficiCedente
		{
			get
			{
				return this._datiAnagraficiCedente;
			}
			set
			{
				this._datiAnagraficiCedente = value;
			}
		}
		
		private IscrizioneREA _iscrizioneREA;
		public virtual IscrizioneREA IscrizioneREA
		{
			get
			{
				return this._iscrizioneREA;
			}
			set
			{
				this._iscrizioneREA = value;
			}
		}
		
	}
}
#pragma warning restore 1591
