#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class CedentePrestatore
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _riferimentoAmministrazione;
		public virtual string RiferimentoAmministrazione
		{
			get
			{
				return this._riferimentoAmministrazione;
			}
			set
			{
				this._riferimentoAmministrazione = value;
			}
		}
		
		private FatturaElettronicaHeader _fatturaElettronicaHeader;
		public virtual FatturaElettronicaHeader FatturaElettronicaHeader
		{
			get
			{
				return this._fatturaElettronicaHeader;
			}
			set
			{
				this._fatturaElettronicaHeader = value;
			}
		}
		
		private IList<Indirizzo> _indirizzos = new List<Indirizzo>();
		public virtual IList<Indirizzo> Indirizzos
		{
			get
			{
				return this._indirizzos;
			}
		}
		
		private IList<Contatti> _contattis = new List<Contatti>();
		public virtual IList<Contatti> Contattis
		{
			get
			{
				return this._contattis;
			}
		}
		
		private IList<DatiAnagraficiCedente> _datiAnagraficiCedentes = new List<DatiAnagraficiCedente>();
		public virtual IList<DatiAnagraficiCedente> DatiAnagraficiCedentes
		{
			get
			{
				return this._datiAnagraficiCedentes;
			}
		}
		
	}
}
#pragma warning restore 1591
