#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class CessionarioCommittente
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private FatturaElettronicaHeader _fatturaElettronicaHeader;
		public virtual FatturaElettronicaHeader FatturaElettronicaHeader
		{
			get
			{
				return this._fatturaElettronicaHeader;
			}
			set
			{
				this._fatturaElettronicaHeader = value;
			}
		}
		
		private IList<Sede> _sedes = new List<Sede>();
		public virtual IList<Sede> Sedes
		{
			get
			{
				return this._sedes;
			}
		}
		
		private DatiAnagraficiCessionario _datiAnagraficiCessionario;
		public virtual DatiAnagraficiCessionario DatiAnagraficiCessionario
		{
			get
			{
				return this._datiAnagraficiCessionario;
			}
			set
			{
				this._datiAnagraficiCessionario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
