#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Contatti
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _telefono;
		public virtual string Telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				this._telefono = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private int _trasmittenteId;
		public virtual int TrasmittenteId
		{
			get
			{
				return this._trasmittenteId;
			}
			set
			{
				this._trasmittenteId = value;
			}
		}
		
		private int _cedentePrestatoreId;
		public virtual int CedentePrestatoreId
		{
			get
			{
				return this._cedentePrestatoreId;
			}
			set
			{
				this._cedentePrestatoreId = value;
			}
		}
		
		private DatiTrasmissione _datiTrasmissione;
		public virtual DatiTrasmissione DatiTrasmissione
		{
			get
			{
				return this._datiTrasmissione;
			}
			set
			{
				this._datiTrasmissione = value;
			}
		}
		
		private CedentePrestatore _cedentePrestatore;
		public virtual CedentePrestatore CedentePrestatore
		{
			get
			{
				return this._cedentePrestatore;
			}
			set
			{
				this._cedentePrestatore = value;
			}
		}
		
	}
}
#pragma warning restore 1591
