#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class DatiAnagraficiCedente
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _codiceFiscale;
		public virtual string CodiceFiscale
		{
			get
			{
				return this._codiceFiscale;
			}
			set
			{
				this._codiceFiscale = value;
			}
		}
		
		private string _alboProfessionale;
		public virtual string AlboProfessionale
		{
			get
			{
				return this._alboProfessionale;
			}
			set
			{
				this._alboProfessionale = value;
			}
		}
		
		private string _provinciaAlbo;
		public virtual string ProvinciaAlbo
		{
			get
			{
				return this._provinciaAlbo;
			}
			set
			{
				this._provinciaAlbo = value;
			}
		}
		
		private string _numeroIscrizioneAlbo;
		public virtual string NumeroIscrizioneAlbo
		{
			get
			{
				return this._numeroIscrizioneAlbo;
			}
			set
			{
				this._numeroIscrizioneAlbo = value;
			}
		}
		
		private DateTime _dataIscrizioneAlbo;
		public virtual DateTime DataIscrizioneAlbo
		{
			get
			{
				return this._dataIscrizioneAlbo;
			}
			set
			{
				this._dataIscrizioneAlbo = value;
			}
		}
		
		private string _regimeFiscale;
		public virtual string RegimeFiscale
		{
			get
			{
				return this._regimeFiscale;
			}
			set
			{
				this._regimeFiscale = value;
			}
		}
		
		private CedentePrestatore _cedentePrestatore;
		public virtual CedentePrestatore CedentePrestatore
		{
			get
			{
				return this._cedentePrestatore;
			}
			set
			{
				this._cedentePrestatore = value;
			}
		}
		
		private IList<IdFiscale> _idFiscales = new List<IdFiscale>();
		public virtual IList<IdFiscale> IdFiscales
		{
			get
			{
				return this._idFiscales;
			}
		}
		
		private Anagrafica _anagrafica;
		public virtual Anagrafica Anagrafica
		{
			get
			{
				return this._anagrafica;
			}
			set
			{
				this._anagrafica = value;
			}
		}
		
	}
}
#pragma warning restore 1591
