#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class DatiBeniServizi
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private DatiGenerali _datiGenerali;
		public virtual DatiGenerali DatiGenerali
		{
			get
			{
				return this._datiGenerali;
			}
			set
			{
				this._datiGenerali = value;
			}
		}
		
		private IList<DettaglioLinee> _dettaglioLinees = new List<DettaglioLinee>();
		public virtual IList<DettaglioLinee> DettaglioLinees
		{
			get
			{
				return this._dettaglioLinees;
			}
		}
		
		private IList<DatiRiepilogo> _datiRiepilogos = new List<DatiRiepilogo>();
		public virtual IList<DatiRiepilogo> DatiRiepilogos
		{
			get
			{
				return this._datiRiepilogos;
			}
		}
		
	}
}
#pragma warning restore 1591
