#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class DatiCassaPrevidenziale
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _datiGeneraliDocumentoId;
		public virtual int DatiGeneraliDocumentoId
		{
			get
			{
				return this._datiGeneraliDocumentoId;
			}
			set
			{
				this._datiGeneraliDocumentoId = value;
			}
		}
		
		private string _tipoCassa;
		public virtual string TipoCassa
		{
			get
			{
				return this._tipoCassa;
			}
			set
			{
				this._tipoCassa = value;
			}
		}
		
		private decimal _alCassa;
		public virtual decimal AlCassa
		{
			get
			{
				return this._alCassa;
			}
			set
			{
				this._alCassa = value;
			}
		}
		
		private decimal _importoContributoCassa;
		public virtual decimal ImportoContributoCassa
		{
			get
			{
				return this._importoContributoCassa;
			}
			set
			{
				this._importoContributoCassa = value;
			}
		}
		
		private decimal _imponibileCassa;
		public virtual decimal ImponibileCassa
		{
			get
			{
				return this._imponibileCassa;
			}
			set
			{
				this._imponibileCassa = value;
			}
		}
		
		private decimal _aliquotaIVA;
		public virtual decimal AliquotaIVA
		{
			get
			{
				return this._aliquotaIVA;
			}
			set
			{
				this._aliquotaIVA = value;
			}
		}
		
		private string _ritenuta;
		public virtual string Ritenuta
		{
			get
			{
				return this._ritenuta;
			}
			set
			{
				this._ritenuta = value;
			}
		}
		
		private string _natura;
		public virtual string Natura
		{
			get
			{
				return this._natura;
			}
			set
			{
				this._natura = value;
			}
		}
		
		private string _riferimentoAmministrazione;
		public virtual string RiferimentoAmministrazione
		{
			get
			{
				return this._riferimentoAmministrazione;
			}
			set
			{
				this._riferimentoAmministrazione = value;
			}
		}
		
		private DatiGeneraliDocumento _datiGeneraliDocumento;
		public virtual DatiGeneraliDocumento DatiGeneraliDocumento
		{
			get
			{
				return this._datiGeneraliDocumento;
			}
			set
			{
				this._datiGeneraliDocumento = value;
			}
		}
		
	}
}
#pragma warning restore 1591
