#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class DatiBollo
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _bolloVirtuale;
		public virtual string BolloVirtuale
		{
			get
			{
				return this._bolloVirtuale;
			}
			set
			{
				this._bolloVirtuale = value;
			}
		}
		
		private decimal _importoBollo;
		public virtual decimal ImportoBollo
		{
			get
			{
				return this._importoBollo;
			}
			set
			{
				this._importoBollo = value;
			}
		}
		
		private DatiGeneraliDocumento _datiGeneraliDocumento;
		public virtual DatiGeneraliDocumento DatiGeneraliDocumento
		{
			get
			{
				return this._datiGeneraliDocumento;
			}
			set
			{
				this._datiGeneraliDocumento = value;
			}
		}
		
	}
}
#pragma warning restore 1591
