#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class DatiAnagraficiCessionario
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _codiceFiscale;
		public virtual string CodiceFiscale
		{
			get
			{
				return this._codiceFiscale;
			}
			set
			{
				this._codiceFiscale = value;
			}
		}
		
		private CessionarioCommittente _cessionarioCommittente;
		public virtual CessionarioCommittente CessionarioCommittente
		{
			get
			{
				return this._cessionarioCommittente;
			}
			set
			{
				this._cessionarioCommittente = value;
			}
		}
		
		private IList<IdFiscale> _idFiscales = new List<IdFiscale>();
		public virtual IList<IdFiscale> IdFiscales
		{
			get
			{
				return this._idFiscales;
			}
		}
		
		private IList<Anagrafica> _anagraficas = new List<Anagrafica>();
		public virtual IList<Anagrafica> Anagraficas
		{
			get
			{
				return this._anagraficas;
			}
		}
		
	}
}
#pragma warning restore 1591
