#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class DettaglioPagamento
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _datiPagamentoId;
		public virtual int DatiPagamentoId
		{
			get
			{
				return this._datiPagamentoId;
			}
			set
			{
				this._datiPagamentoId = value;
			}
		}
		
		private string _beneficiario;
		public virtual string Beneficiario
		{
			get
			{
				return this._beneficiario;
			}
			set
			{
				this._beneficiario = value;
			}
		}
		
		private string _modalitaPagamento;
		public virtual string ModalitaPagamento
		{
			get
			{
				return this._modalitaPagamento;
			}
			set
			{
				this._modalitaPagamento = value;
			}
		}
		
		private DateTime _dataRiferimentoTerminiPagamento;
		public virtual DateTime DataRiferimentoTerminiPagamento
		{
			get
			{
				return this._dataRiferimentoTerminiPagamento;
			}
			set
			{
				this._dataRiferimentoTerminiPagamento = value;
			}
		}
		
		private int _giorniTerminiPagamento;
		public virtual int GiorniTerminiPagamento
		{
			get
			{
				return this._giorniTerminiPagamento;
			}
			set
			{
				this._giorniTerminiPagamento = value;
			}
		}
		
		private decimal _dataScadenzaPagamento;
		public virtual decimal DataScadenzaPagamento
		{
			get
			{
				return this._dataScadenzaPagamento;
			}
			set
			{
				this._dataScadenzaPagamento = value;
			}
		}
		
		private string _importoPagamento;
		public virtual string ImportoPagamento
		{
			get
			{
				return this._importoPagamento;
			}
			set
			{
				this._importoPagamento = value;
			}
		}
		
		private string _iBAN;
		public virtual string IBAN
		{
			get
			{
				return this._iBAN;
			}
			set
			{
				this._iBAN = value;
			}
		}
		
		private DatiPagamento _datiPagamento;
		public virtual DatiPagamento DatiPagamento
		{
			get
			{
				return this._datiPagamento;
			}
			set
			{
				this._datiPagamento = value;
			}
		}
		
	}
}
#pragma warning restore 1591
