#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class DettaglioLinee
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _datiBeniServiziId;
		public virtual int DatiBeniServiziId
		{
			get
			{
				return this._datiBeniServiziId;
			}
			set
			{
				this._datiBeniServiziId = value;
			}
		}
		
		private string _numeroLinea;
		public virtual string NumeroLinea
		{
			get
			{
				return this._numeroLinea;
			}
			set
			{
				this._numeroLinea = value;
			}
		}
		
		private string _descrizione;
		public virtual string Descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				this._descrizione = value;
			}
		}
		
		private decimal _prezzoUnitario;
		public virtual decimal PrezzoUnitario
		{
			get
			{
				return this._prezzoUnitario;
			}
			set
			{
				this._prezzoUnitario = value;
			}
		}
		
		private decimal _prezzoTotale;
		public virtual decimal PrezzoTotale
		{
			get
			{
				return this._prezzoTotale;
			}
			set
			{
				this._prezzoTotale = value;
			}
		}
		
		private decimal _aliquotaIVA;
		public virtual decimal AliquotaIVA
		{
			get
			{
				return this._aliquotaIVA;
			}
			set
			{
				this._aliquotaIVA = value;
			}
		}
		
		private string _ritenuta;
		public virtual string Ritenuta
		{
			get
			{
				return this._ritenuta;
			}
			set
			{
				this._ritenuta = value;
			}
		}
		
		private DateTime _dataInizioPeriodo;
		public virtual DateTime DataInizioPeriodo
		{
			get
			{
				return this._dataInizioPeriodo;
			}
			set
			{
				this._dataInizioPeriodo = value;
			}
		}
		
		private DateTime _dataFinePeriodo;
		public virtual DateTime DataFinePeriodo
		{
			get
			{
				return this._dataFinePeriodo;
			}
			set
			{
				this._dataFinePeriodo = value;
			}
		}
		
		private DatiBeniServizi _datiBeniServizi;
		public virtual DatiBeniServizi DatiBeniServizi
		{
			get
			{
				return this._datiBeniServizi;
			}
			set
			{
				this._datiBeniServizi = value;
			}
		}
		
	}
}
#pragma warning restore 1591
