#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class FatturaElettronicaHeader
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _soggettoEmittente;
		public virtual string SoggettoEmittente
		{
			get
			{
				return this._soggettoEmittente;
			}
			set
			{
				this._soggettoEmittente = value;
			}
		}
		
		private Fattura _fattura;
		public virtual Fattura Fattura
		{
			get
			{
				return this._fattura;
			}
			set
			{
				this._fattura = value;
			}
		}
		
		private DatiTrasmissione _datiTrasmissione;
		public virtual DatiTrasmissione DatiTrasmissione
		{
			get
			{
				return this._datiTrasmissione;
			}
			set
			{
				this._datiTrasmissione = value;
			}
		}
		
		private CedentePrestatore _cedentePrestatore;
		public virtual CedentePrestatore CedentePrestatore
		{
			get
			{
				return this._cedentePrestatore;
			}
			set
			{
				this._cedentePrestatore = value;
			}
		}
		
		private CessionarioCommittente _cessionarioCommittente;
		public virtual CessionarioCommittente CessionarioCommittente
		{
			get
			{
				return this._cessionarioCommittente;
			}
			set
			{
				this._cessionarioCommittente = value;
			}
		}
		
	}
}
#pragma warning restore 1591
