#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class IdTrasmissione
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _idPaese;
		public virtual string IdPaese
		{
			get
			{
				return this._idPaese;
			}
			set
			{
				this._idPaese = value;
			}
		}
		
		private string _idCodice;
		public virtual string IdCodice
		{
			get
			{
				return this._idCodice;
			}
			set
			{
				this._idCodice = value;
			}
		}
		
		private DatiTrasmissione _datiTrasmissione;
		public virtual DatiTrasmissione DatiTrasmissione
		{
			get
			{
				return this._datiTrasmissione;
			}
			set
			{
				this._datiTrasmissione = value;
			}
		}
		
	}
}
#pragma warning restore 1591
