#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class IscrizioneREA
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _ufficio;
		public virtual string Ufficio
		{
			get
			{
				return this._ufficio;
			}
			set
			{
				this._ufficio = value;
			}
		}
		
		private string _numeroREA;
		public virtual string NumeroREA
		{
			get
			{
				return this._numeroREA;
			}
			set
			{
				this._numeroREA = value;
			}
		}
		
		private string _capitaleSociale;
		public virtual string CapitaleSociale
		{
			get
			{
				return this._capitaleSociale;
			}
			set
			{
				this._capitaleSociale = value;
			}
		}
		
		private string _socioUnico;
		public virtual string SocioUnico
		{
			get
			{
				return this._socioUnico;
			}
			set
			{
				this._socioUnico = value;
			}
		}
		
		private string _statoLiquidazione;
		public virtual string StatoLiquidazione
		{
			get
			{
				return this._statoLiquidazione;
			}
			set
			{
				this._statoLiquidazione = value;
			}
		}
		
		private CedentePrestatore _cedentePrestatore;
		public virtual CedentePrestatore CedentePrestatore
		{
			get
			{
				return this._cedentePrestatore;
			}
			set
			{
				this._cedentePrestatore = value;
			}
		}
		
	}
}
#pragma warning restore 1591
