#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class ScontoMaggiorazione
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _datiGeneraliDocumentoId;
		public virtual int DatiGeneraliDocumentoId
		{
			get
			{
				return this._datiGeneraliDocumentoId;
			}
			set
			{
				this._datiGeneraliDocumentoId = value;
			}
		}
		
		private string _tipo;
		public virtual string Tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				this._tipo = value;
			}
		}
		
		private decimal _percentuale;
		public virtual decimal Percentuale
		{
			get
			{
				return this._percentuale;
			}
			set
			{
				this._percentuale = value;
			}
		}
		
		private decimal _importo;
		public virtual decimal Importo
		{
			get
			{
				return this._importo;
			}
			set
			{
				this._importo = value;
			}
		}
		
		private DatiGeneraliDocumento _datiGeneraliDocumento;
		public virtual DatiGeneraliDocumento DatiGeneraliDocumento
		{
			get
			{
				return this._datiGeneraliDocumento;
			}
			set
			{
				this._datiGeneraliDocumento = value;
			}
		}
		
	}
}
#pragma warning restore 1591
