#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Sede : Indirizzo
	{
		private int _id;
		public override int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _cedentePrestatoreId;
		public virtual int CedentePrestatoreId
		{
			get
			{
				return this._cedentePrestatoreId;
			}
			set
			{
				this._cedentePrestatoreId = value;
			}
		}
		
		private int _cessionarioCommittenteId;
		public virtual int CessionarioCommittenteId
		{
			get
			{
				return this._cessionarioCommittenteId;
			}
			set
			{
				this._cessionarioCommittenteId = value;
			}
		}
		
		private CedentePrestatore _cedentePrestatore;
		public virtual CedentePrestatore CedentePrestatore
		{
			get
			{
				return this._cedentePrestatore;
			}
			set
			{
				this._cedentePrestatore = value;
			}
		}
		
		private CessionarioCommittente _cessionarioCommittente;
		public virtual CessionarioCommittente CessionarioCommittente
		{
			get
			{
				return this._cessionarioCommittente;
			}
			set
			{
				this._cessionarioCommittente = value;
			}
		}
		
	}
}
#pragma warning restore 1591
