#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Trasmissione
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _fatturaId;
		public virtual int FatturaId
		{
			get
			{
				return this._fatturaId;
			}
			set
			{
				this._fatturaId = value;
			}
		}
		
		private int _studioProfessionaleId;
		public virtual int StudioProfessionaleId
		{
			get
			{
				return this._studioProfessionaleId;
			}
			set
			{
				this._studioProfessionaleId = value;
			}
		}
		
		private string _stato;
		public virtual string Stato
		{
			get
			{
				return this._stato;
			}
			set
			{
				this._stato = value;
			}
		}
		
		private DateTime _trasmessa;
		public virtual DateTime Trasmessa
		{
			get
			{
				return this._trasmessa;
			}
			set
			{
				this._trasmessa = value;
			}
		}
		
		private string _xmlFile;
		public virtual string XmlFile
		{
			get
			{
				return this._xmlFile;
			}
			set
			{
				this._xmlFile = value;
			}
		}
		
		private Fattura _fattura;
		public virtual Fattura Fattura
		{
			get
			{
				return this._fattura;
			}
			set
			{
				this._fattura = value;
			}
		}
		
		private StudioProfessionale _studioProfessionale;
		public virtual StudioProfessionale StudioProfessionale
		{
			get
			{
				return this._studioProfessionale;
			}
			set
			{
				this._studioProfessionale = value;
			}
		}
		
	}
}
#pragma warning restore 1591
